import { useState } from "react";
import { AnimatePresence, motion } from "motion/react";
import { Expand, Images, Presentation, X } from "lucide-react";
import { Hero } from "@/shared/ui/hero";

const results = [
  { src: "/gallery/bathymetry-overview.svg", title: "Обзор батиметрии", type: "SVG", category: "Рельеф" },
  { src: "/gallery/adaptive-size-field.svg", title: "Адаптивное поле размеров", type: "SVG", category: "Сетки" },
  { src: "/gallery/erosion-step-0.svg", title: "Эрозия · начальное состояние", type: "SVG", category: "Динамика" },
  { src: "/gallery/erosion-step-3.svg", title: "Эрозия · шаг 3", type: "SVG", category: "Динамика" },
  { src: "/gallery/lithology-map.png", title: "Карта литологии", type: "PNG", category: "Материалы" },
  { src: "/gallery/dynamics.png", title: "Временная динамика", type: "PNG", category: "Динамика" },
  { src: "/gallery/sediment-budget.png", title: "Баланс наносов", type: "PNG", category: "Метрики" },
];

export function GalleryPage() {
  const [selected, setSelected] = useState<(typeof results)[number] | null>(null);
  return <div className="space-y-10"><Hero title="Галерея результатов" subtitle="Как Litora видит прибрежную систему" /><div className="flex items-start gap-3 rounded-2xl border border-primary/20 bg-primary/[0.06] p-5"><Images className="mt-1 size-5 shrink-0 text-primary" /><p className="text-sm leading-6 text-muted-foreground">Реальные карты, сетки и отчёты, собранные CLI в научных сценариях. Нажмите на карточку, чтобы рассмотреть результат.</p></div><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{results.map((result, index) => <motion.button key={result.src} type="button" onClick={() => setSelected(result)} initial={{ opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * 0.06 }} className="group overflow-hidden rounded-2xl border bg-background text-left shadow-sm transition-all hover:-translate-y-1 hover:border-primary/50 hover:shadow-xl"><div className="flex aspect-[4/3] items-center justify-center overflow-hidden bg-muted/30 p-3"><img src={result.src} alt={result.title} className="max-h-full max-w-full object-contain transition-transform duration-500 group-hover:scale-105" /></div><div className="flex items-center justify-between p-4"><div><p className="text-xs text-primary">{result.category} · {result.type}</p><h2 className="mt-1 font-semibold">{result.title}</h2></div><Expand className="size-4 text-muted-foreground" /></div></motion.button>)}</div><section className="rounded-2xl border border-dashed p-6 sm:p-8"><div className="flex items-start gap-4"><Presentation className="size-6 text-primary" /><div><h2 className="text-xl font-bold">Презентации проекта</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">Здесь появится интерактивный просмотр презентаций: научный контекст, методика, результаты экспериментов и развитие Litora.</p><span className="mt-4 inline-flex rounded-full bg-muted px-3 py-1 text-xs text-muted-foreground">Скоро</span></div></div></section><AnimatePresence>{selected && <motion.div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 p-4" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={() => setSelected(null)}><motion.div className="relative max-h-[90vh] max-w-6xl rounded-2xl bg-background p-3 shadow-2xl" initial={{ scale: 0.95 }} animate={{ scale: 1 }} onClick={(event) => event.stopPropagation()}><button type="button" aria-label="Закрыть" onClick={() => setSelected(null)} className="absolute top-3 right-3 z-10 rounded-full bg-background/90 p-2 shadow hover:text-primary"><X className="size-5" /></button><img src={selected.src} alt={selected.title} className="max-h-[82vh] max-w-full object-contain" /><p className="px-2 pt-2 text-sm font-medium">{selected.title}</p></motion.div></motion.div>}</AnimatePresence></div>;
}
