package cli

import (
	"coastal-geometry/internal/domain/coastline"
	"coastal-geometry/internal/domain/generators/koch"
	"fmt"
	"io"
	"os"
	"path/filepath"
)

func printRootUsage(w io.Writer) {
	bin := filepath.Base(os.Args[0])
	fmt.Fprintf(w, "Usage: %s <command> [flags]\n\n", bin)
	fmt.Fprintln(w, "Purpose:")
	fmt.Fprintln(w, "  validate coastline geometry, measure length geodesically, and")
	fmt.Fprintln(w, "  demonstrate fractal properties mathematically correctly.")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "Commands:")
	fmt.Fprintf(w, "  %-10s run the full validation and fractal-analysis pipeline\n", cmdAll)
	fmt.Fprintf(w, "  %-10s validate geometry, measure coastline length, and save coastline.svg\n", cmdCoastline)
	fmt.Fprintf(w, "  %-10s run the mathematically correct coastline paradox demo\n", cmdParadox)
	fmt.Fprintf(w, "  %-10s run classic Koch analysis and save koch_iter_0..N.svg\n", cmdKoch)
	fmt.Fprintf(w, "  %-10s run organic coastline-fractal analysis and save koch_iter_0..N.svg\n", cmdKochOrganic)
	fmt.Fprintf(w, "  %-10s compute box-counting dimension and test convergence\n", cmdDimension)
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "Examples:")
	fmt.Fprintf(w, "  %s coastline\n", bin)
	fmt.Fprintf(w, "  %s koch --iterations 4 --output ./output/koch\n", bin)
	fmt.Fprintf(w, "  %s koch-organic --iterations 4 --seed 42 --angle-jitter 18 --height-jitter 0.25 --output ./output/koch-organic\n", bin)
	fmt.Fprintf(w, "  %s dimension --iterations 6 --input data/black-sea.json\n", bin)
	fmt.Fprintf(w, "  %s all --output ./output/full-run\n", bin)
	fmt.Fprintln(w, "")
	fmt.Fprintf(w, "Run '%s <command> --help' for command-specific flags.\n", bin)
}

func printCommandUsage(w io.Writer, command string) {
	bin := filepath.Base(os.Args[0])
	switch command {
	case cmdAll:
		fmt.Fprintf(w, "Usage: %s %s [flags]\n\n", bin, cmdAll)
		fmt.Fprintln(w, "Runs the full analytical pipeline: geometry validation, geodesic length, paradox demo, organic fractal growth, and box-counting diagnostics.")
		fmt.Fprintln(w, "")
		fmt.Fprintln(w, "Flags:")
		fmt.Fprintln(w, "  --input string")
		fmt.Fprintf(w, "        path to coastline JSON file (default %q)\n", coastline.DefaultCoastlineJSONPath)
		fmt.Fprintln(w, "  --iterations int")
		fmt.Fprintf(w, "        maximum organic Koch iterations (0-%d)\n", koch.MaxIterations)
		fmt.Fprintln(w, "  --seed int")
		fmt.Fprintln(w, "        random seed for organic coastline generation")
		fmt.Fprintln(w, "  --angle-jitter float")
		fmt.Fprintln(w, "        maximum random angle deviation in degrees")
		fmt.Fprintln(w, "  --height-jitter float")
		fmt.Fprintln(w, "        maximum random height deviation as a ratio")
		fmt.Fprintln(w, "  --output string")
		fmt.Fprintln(w, "        output directory for generated visualizations (default: ./output)")
	case cmdCoastline:
		fmt.Fprintf(w, "Usage: %s %s [flags]\n\n", bin, cmdCoastline)
		fmt.Fprintln(w, "Validates coastline geometry, measures length geodesically, and saves a coastline SVG report.")
		fmt.Fprintln(w, "")
		fmt.Fprintln(w, "Flags:")
		fmt.Fprintln(w, "  --input string")
		fmt.Fprintf(w, "        path to coastline JSON file (default %q)\n", coastline.DefaultCoastlineJSONPath)
		fmt.Fprintln(w, "  --output string")
		fmt.Fprintln(w, "        output SVG path or directory (default: ./output)")
	case cmdParadox:
		fmt.Fprintf(w, "Usage: %s %s [flags]\n\n", bin, cmdParadox)
		fmt.Fprintln(w, "Runs the coastline paradox demonstration using scale-dependent geometry refinement instead of simple subdivision.")
		fmt.Fprintln(w, "")
		fmt.Fprintln(w, "Flags:")
		fmt.Fprintln(w, "  --input string")
		fmt.Fprintf(w, "        path to coastline JSON file (default %q)\n", coastline.DefaultCoastlineJSONPath)
		fmt.Fprintln(w, "  --iterations int")
		fmt.Fprintf(w, "        maximum paradox detail levels (0-%d)\n", koch.MaxIterations)
	case cmdKoch:
		fmt.Fprintf(w, "Usage: %s %s [flags]\n\n", bin, cmdKoch)
		fmt.Fprintln(w, "Builds a classic Koch curve, checks measured length against theory, and saves koch_iter_0..N.svg.")
		fmt.Fprintln(w, "")
		fmt.Fprintln(w, "Flags:")
		fmt.Fprintln(w, "  --input string")
		fmt.Fprintf(w, "        path to coastline JSON file (default %q)\n", coastline.DefaultCoastlineJSONPath)
		fmt.Fprintln(w, "  --iterations int")
		fmt.Fprintf(w, "        maximum Koch iterations (0-%d)\n", koch.MaxIterations)
		fmt.Fprintln(w, "  --output string")
		fmt.Fprintln(w, "        output directory for generated visualizations (default: ./output)")
	case cmdKochOrganic:
		fmt.Fprintf(w, "Usage: %s %s [flags]\n\n", bin, cmdKochOrganic)
		fmt.Fprintln(w, "Builds an organic coastline-growth approximation for analysis of natural-looking fractal detail and saves koch_iter_0..N.svg.")
		fmt.Fprintln(w, "")
		fmt.Fprintln(w, "Flags:")
		fmt.Fprintln(w, "  --input string")
		fmt.Fprintf(w, "        path to coastline JSON file (default %q)\n", coastline.DefaultCoastlineJSONPath)
		fmt.Fprintln(w, "  --iterations int")
		fmt.Fprintf(w, "        maximum organic Koch iterations (0-%d)\n", koch.MaxIterations)
		fmt.Fprintln(w, "  --seed int")
		fmt.Fprintln(w, "        random seed for organic coastline generation")
		fmt.Fprintln(w, "  --angle-jitter float")
		fmt.Fprintln(w, "        maximum random angle deviation in degrees")
		fmt.Fprintln(w, "  --height-jitter float")
		fmt.Fprintln(w, "        maximum random height deviation as a ratio")
		fmt.Fprintln(w, "  --output string")
		fmt.Fprintln(w, "        output directory for generated visualizations (default: ./output)")
	case cmdDimension:
		fmt.Fprintf(w, "Usage: %s %s [flags]\n\n", bin, cmdDimension)
		fmt.Fprintln(w, "Computes empirical box-counting dimension across organic coastline-growth iterations, checks convergence, and saves koch_iter_0..N.svg.")
		fmt.Fprintln(w, "")
		fmt.Fprintln(w, "Flags:")
		fmt.Fprintln(w, "  --input string")
		fmt.Fprintf(w, "        path to coastline JSON file (default %q)\n", coastline.DefaultCoastlineJSONPath)
		fmt.Fprintln(w, "  --iterations int")
		fmt.Fprintf(w, "        maximum organic Koch iterations (0-%d)\n", koch.MaxIterations)
		fmt.Fprintln(w, "  --seed int")
		fmt.Fprintln(w, "        random seed for organic coastline generation")
		fmt.Fprintln(w, "  --angle-jitter float")
		fmt.Fprintln(w, "        maximum random angle deviation in degrees")
		fmt.Fprintln(w, "  --height-jitter float")
		fmt.Fprintln(w, "        maximum random height deviation as a ratio")
		fmt.Fprintln(w, "  --output string")
		fmt.Fprintln(w, "        output directory for generated visualizations (default: ./output)")
	}
}
