package cli

import (
	"coastal-geometry/internal/domain/coastline"
	"coastal-geometry/internal/domain/generators/koch"
	"fmt"
	"io"
	"os"
	"path/filepath"
)

func printRootUsage(w io.Writer) {
	bin := filepath.Base(os.Args[0])
	fmt.Fprintf(w, "Usage: %s %s <command> [flags]\n", bin, cmdReal)
	fmt.Fprintf(w, "       %s %s <command> [flags]\n", bin, cmdModel)
	fmt.Fprintf(w, "       %s %s [flags]\n\n", bin, cmdAll)
	fmt.Fprintln(w, "Purpose:")
	fmt.Fprintln(w, "  validate coastline geometry, measure length geodesically, and")
	fmt.Fprintln(w, "  demonstrate fractal properties mathematically correctly.")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "Command Groups:")
	fmt.Fprintln(w, "  Real-data analysis:")
	fmt.Fprintf(w, "    %-18s %s\n", canonicalCommandPath(cmdCoastline), getCommandUX(cmdCoastline).Summary)
	fmt.Fprintln(w, "  Synthetic demonstrations:")
	fmt.Fprintf(w, "    %-18s %s\n", canonicalCommandPath(cmdParadox), getCommandUX(cmdParadox).Summary)
	fmt.Fprintf(w, "    %-18s %s\n", canonicalCommandPath(cmdKoch), getCommandUX(cmdKoch).Summary)
	fmt.Fprintf(w, "    %-18s %s\n", canonicalCommandPath(cmdKochOrganic), getCommandUX(cmdKochOrganic).Summary)
	fmt.Fprintf(w, "    %-18s %s\n", canonicalCommandPath(cmdDimension), getCommandUX(cmdDimension).Summary)
	fmt.Fprintln(w, "  Mixed pipeline:")
	fmt.Fprintf(w, "    %-18s %s\n", cmdAll, getCommandUX(cmdAll).Summary)
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "Compatibility aliases:")
	fmt.Fprintf(w, "  %s %s        -> %s %s\n", bin, cmdCoastline, bin, canonicalCommandPath(cmdCoastline))
	fmt.Fprintf(w, "  %s %s          -> %s %s\n", bin, cmdParadox, bin, canonicalCommandPath(cmdParadox))
	fmt.Fprintf(w, "  %s %s             -> %s %s\n", bin, cmdKoch, bin, canonicalCommandPath(cmdKoch))
	fmt.Fprintf(w, "  %s %s     -> %s %s\n", bin, cmdKochOrganic, bin, canonicalCommandPath(cmdKochOrganic))
	fmt.Fprintf(w, "  %s %s        -> %s %s\n", bin, cmdDimension, bin, canonicalCommandPath(cmdDimension))
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "Examples:")
	fmt.Fprintf(w, "  %s %s\n", bin, canonicalCommandPath(cmdCoastline))
	fmt.Fprintf(w, "  %s %s --source-url %s\n", bin, canonicalCommandPath(cmdCoastline), coastline.DefaultCoastlineGeoJSONURL)
	fmt.Fprintf(w, "  %s %s --iterations 4 --output ./output/koch\n", bin, canonicalCommandPath(cmdKoch))
	fmt.Fprintf(w, "  %s %s --iterations 4 --seed 42 --angle-jitter 18 --height-jitter 0.25 --output ./output/koch-organic\n", bin, canonicalCommandPath(cmdKochOrganic))
	fmt.Fprintf(w, "  %s %s --iterations 6 --input data/black-sea.json\n", bin, canonicalCommandPath(cmdDimension))
	fmt.Fprintf(w, "  %s all --output ./output/full-run\n", bin)
	fmt.Fprintln(w, "")
	fmt.Fprintf(w, "Run '%s %s <command> --help', '%s %s <command> --help', or '%s all --help'.\n", bin, cmdReal, bin, cmdModel, bin)
}

func printGroupUsage(w io.Writer, group string) {
	bin := filepath.Base(os.Args[0])

	switch group {
	case cmdReal:
		fmt.Fprintf(w, "Usage: %s %s <command> [flags]\n\n", bin, cmdReal)
		fmt.Fprintln(w, "Group:")
		fmt.Fprintln(w, "  direct calculations on the loaded coastline data itself")
		fmt.Fprintln(w, "")
		fmt.Fprintln(w, "Commands:")
		fmt.Fprintf(w, "  %-12s %s\n", cmdCoastline, getCommandUX(cmdCoastline).Summary)
		fmt.Fprintln(w, "")
		fmt.Fprintln(w, "Examples:")
		fmt.Fprintf(w, "  %s %s\n", bin, canonicalCommandPath(cmdCoastline))
		fmt.Fprintf(w, "  %s %s --source-url %s\n", bin, canonicalCommandPath(cmdCoastline), coastline.DefaultCoastlineGeoJSONURL)
		fmt.Fprintln(w, "")
		fmt.Fprintf(w, "Legacy alias: %s %s\n", bin, cmdCoastline)
	case cmdModel:
		fmt.Fprintf(w, "Usage: %s %s <command> [flags]\n\n", bin, cmdModel)
		fmt.Fprintln(w, "Group:")
		fmt.Fprintln(w, "  synthetic demonstrations derived from the loaded coastline base geometry")
		fmt.Fprintln(w, "")
		fmt.Fprintln(w, "Commands:")
		fmt.Fprintf(w, "  %-12s %s\n", cmdParadox, getCommandUX(cmdParadox).Summary)
		fmt.Fprintf(w, "  %-12s %s\n", cmdKoch, getCommandUX(cmdKoch).Summary)
		fmt.Fprintf(w, "  %-12s %s\n", cmdKochOrganic, getCommandUX(cmdKochOrganic).Summary)
		fmt.Fprintf(w, "  %-12s %s\n", cmdDimension, getCommandUX(cmdDimension).Summary)
		fmt.Fprintln(w, "")
		fmt.Fprintln(w, "Examples:")
		fmt.Fprintf(w, "  %s %s --iterations 1\n", bin, canonicalCommandPath(cmdParadox))
		fmt.Fprintf(w, "  %s %s --iterations 4 --output ./output/koch\n", bin, canonicalCommandPath(cmdKoch))
		fmt.Fprintf(w, "  %s %s --iterations 4 --seed 42 --angle-jitter 18 --height-jitter 0.25 --output ./output/koch-organic\n", bin, canonicalCommandPath(cmdKochOrganic))
		fmt.Fprintf(w, "  %s %s --iterations 6 --output ./output/dimension\n", bin, canonicalCommandPath(cmdDimension))
		fmt.Fprintln(w, "")
		fmt.Fprintf(w, "Legacy aliases: %s %s, %s %s, %s %s, %s %s\n",
			bin, cmdParadox,
			bin, cmdKoch,
			bin, cmdKochOrganic,
			bin, cmdDimension)
	}
}

func printCommandUsage(w io.Writer, command string) {
	bin := filepath.Base(os.Args[0])
	usagePath := canonicalCommandPath(command)
	alias := legacyAlias(command)

	switch command {
	case cmdAll:
		fmt.Fprintf(w, "Usage: %s %s [flags]\n\n", bin, cmdAll)
		ux := getCommandUX(command)
		fmt.Fprintln(w, "Runs the full analytical pipeline: geometry validation, geodesic length, paradox demo, organic fractal growth, and box-counting diagnostics.")
		fmt.Fprintln(w, "")
		fmt.Fprintf(w, "Mode: %s\n", ux.Mode)
		fmt.Fprintf(w, "Note: %s\n", ux.RuntimeNote)
		fmt.Fprintln(w, "")
		fmt.Fprintln(w, "Flags:")
		fmt.Fprintln(w, "  --input string")
		fmt.Fprintf(w, "        path to local coastline JSON/GeoJSON fallback file (default %q)\n", coastline.DefaultCoastlineJSONPath)
		fmt.Fprintln(w, "  --source-url string")
		fmt.Fprintf(w, "        remote GeoJSON URL for coastline data (default %q; empty string disables HTTP loading)\n", coastline.DefaultCoastlineGeoJSONURL)
		fmt.Fprintln(w, "  --refresh")
		fmt.Fprintln(w, "        force refresh of the remote GeoJSON cache before running")
		fmt.Fprintln(w, "  --iterations int")
		fmt.Fprintf(w, "        maximum organic Koch iterations (0-%d)\n", koch.MaxIterations)
		fmt.Fprintln(w, "  --seed int")
		fmt.Fprintln(w, "        random seed for organic coastline generation")
		fmt.Fprintln(w, "  --angle-jitter float")
		fmt.Fprintln(w, "        maximum random angle deviation in degrees")
		fmt.Fprintln(w, "  --height-jitter float")
		fmt.Fprintln(w, "        maximum random height deviation as a ratio")
		fmt.Fprintln(w, "  --output string")
		fmt.Fprintln(w, "        output directory for generated visualizations (default: ./output)")
	case cmdCoastline:
		fmt.Fprintf(w, "Usage: %s %s [flags]\n\n", bin, usagePath)
		ux := getCommandUX(command)
		fmt.Fprintln(w, "Validates coastline geometry, measures length geodesically, and saves a coastline SVG report.")
		fmt.Fprintln(w, "")
		fmt.Fprintf(w, "Mode: %s\n", ux.Mode)
		fmt.Fprintf(w, "Note: %s\n", ux.RuntimeNote)
		fmt.Fprintf(w, "Legacy alias: %s %s\n", bin, alias)
		fmt.Fprintln(w, "")
		fmt.Fprintln(w, "Flags:")
		fmt.Fprintln(w, "  --input string")
		fmt.Fprintf(w, "        path to local coastline JSON/GeoJSON fallback file (default %q)\n", coastline.DefaultCoastlineJSONPath)
		fmt.Fprintln(w, "  --source-url string")
		fmt.Fprintf(w, "        remote GeoJSON URL for coastline data (default %q; empty string disables HTTP loading)\n", coastline.DefaultCoastlineGeoJSONURL)
		fmt.Fprintln(w, "  --refresh")
		fmt.Fprintln(w, "        force refresh of the remote GeoJSON cache before running")
		fmt.Fprintln(w, "  --output string")
		fmt.Fprintln(w, "        output SVG path or directory (default: ./output)")
	case cmdParadox:
		fmt.Fprintf(w, "Usage: %s %s [flags]\n\n", bin, usagePath)
		ux := getCommandUX(command)
		fmt.Fprintln(w, "Runs the coastline paradox demonstration using scale-dependent geometry refinement instead of simple subdivision.")
		fmt.Fprintln(w, "")
		fmt.Fprintf(w, "Mode: %s\n", ux.Mode)
		fmt.Fprintf(w, "Note: %s\n", ux.RuntimeNote)
		fmt.Fprintf(w, "Legacy alias: %s %s\n", bin, alias)
		fmt.Fprintln(w, "")
		fmt.Fprintln(w, "Flags:")
		fmt.Fprintln(w, "  --input string")
		fmt.Fprintf(w, "        path to local coastline JSON/GeoJSON fallback file (default %q)\n", coastline.DefaultCoastlineJSONPath)
		fmt.Fprintln(w, "  --source-url string")
		fmt.Fprintf(w, "        remote GeoJSON URL for coastline data (default %q; empty string disables HTTP loading)\n", coastline.DefaultCoastlineGeoJSONURL)
		fmt.Fprintln(w, "  --refresh")
		fmt.Fprintln(w, "        force refresh of the remote GeoJSON cache before running")
		fmt.Fprintln(w, "  --iterations int")
		fmt.Fprintf(w, "        maximum paradox detail levels (0-%d)\n", koch.MaxIterations)
	case cmdKoch:
		fmt.Fprintf(w, "Usage: %s %s [flags]\n\n", bin, usagePath)
		ux := getCommandUX(command)
		fmt.Fprintln(w, "Builds a classic Koch curve, checks measured length against theory, and saves koch_iter_0..N.svg.")
		fmt.Fprintln(w, "")
		fmt.Fprintf(w, "Mode: %s\n", ux.Mode)
		fmt.Fprintf(w, "Note: %s\n", ux.RuntimeNote)
		fmt.Fprintf(w, "Legacy alias: %s %s\n", bin, alias)
		fmt.Fprintln(w, "")
		fmt.Fprintln(w, "Flags:")
		fmt.Fprintln(w, "  --input string")
		fmt.Fprintf(w, "        path to local coastline JSON/GeoJSON fallback file (default %q)\n", coastline.DefaultCoastlineJSONPath)
		fmt.Fprintln(w, "  --source-url string")
		fmt.Fprintf(w, "        remote GeoJSON URL for coastline data (default %q; empty string disables HTTP loading)\n", coastline.DefaultCoastlineGeoJSONURL)
		fmt.Fprintln(w, "  --refresh")
		fmt.Fprintln(w, "        force refresh of the remote GeoJSON cache before running")
		fmt.Fprintln(w, "  --iterations int")
		fmt.Fprintf(w, "        maximum Koch iterations (0-%d)\n", koch.MaxIterations)
		fmt.Fprintln(w, "  --output string")
		fmt.Fprintln(w, "        output directory for generated visualizations (default: ./output)")
	case cmdKochOrganic:
		fmt.Fprintf(w, "Usage: %s %s [flags]\n\n", bin, usagePath)
		ux := getCommandUX(command)
		fmt.Fprintln(w, "Builds an organic coastline-growth approximation for analysis of natural-looking fractal detail and saves koch_iter_0..N.svg.")
		fmt.Fprintln(w, "")
		fmt.Fprintf(w, "Mode: %s\n", ux.Mode)
		fmt.Fprintf(w, "Note: %s\n", ux.RuntimeNote)
		fmt.Fprintf(w, "Legacy alias: %s %s\n", bin, alias)
		fmt.Fprintln(w, "")
		fmt.Fprintln(w, "Flags:")
		fmt.Fprintln(w, "  --input string")
		fmt.Fprintf(w, "        path to local coastline JSON/GeoJSON fallback file (default %q)\n", coastline.DefaultCoastlineJSONPath)
		fmt.Fprintln(w, "  --source-url string")
		fmt.Fprintf(w, "        remote GeoJSON URL for coastline data (default %q; empty string disables HTTP loading)\n", coastline.DefaultCoastlineGeoJSONURL)
		fmt.Fprintln(w, "  --refresh")
		fmt.Fprintln(w, "        force refresh of the remote GeoJSON cache before running")
		fmt.Fprintln(w, "  --iterations int")
		fmt.Fprintf(w, "        maximum organic Koch iterations (0-%d)\n", koch.MaxIterations)
		fmt.Fprintln(w, "  --seed int")
		fmt.Fprintln(w, "        random seed for organic coastline generation")
		fmt.Fprintln(w, "  --angle-jitter float")
		fmt.Fprintln(w, "        maximum random angle deviation in degrees")
		fmt.Fprintln(w, "  --height-jitter float")
		fmt.Fprintln(w, "        maximum random height deviation as a ratio")
		fmt.Fprintln(w, "  --output string")
		fmt.Fprintln(w, "        output directory for generated visualizations (default: ./output)")
	case cmdDimension:
		fmt.Fprintf(w, "Usage: %s %s [flags]\n\n", bin, usagePath)
		ux := getCommandUX(command)
		fmt.Fprintln(w, "Computes empirical box-counting dimension across organic coastline-growth iterations, checks convergence, and saves koch_iter_0..N.svg.")
		fmt.Fprintln(w, "")
		fmt.Fprintf(w, "Mode: %s\n", ux.Mode)
		fmt.Fprintf(w, "Note: %s\n", ux.RuntimeNote)
		fmt.Fprintf(w, "Legacy alias: %s %s\n", bin, alias)
		fmt.Fprintln(w, "")
		fmt.Fprintln(w, "Flags:")
		fmt.Fprintln(w, "  --input string")
		fmt.Fprintf(w, "        path to local coastline JSON/GeoJSON fallback file (default %q)\n", coastline.DefaultCoastlineJSONPath)
		fmt.Fprintln(w, "  --source-url string")
		fmt.Fprintf(w, "        remote GeoJSON URL for coastline data (default %q; empty string disables HTTP loading)\n", coastline.DefaultCoastlineGeoJSONURL)
		fmt.Fprintln(w, "  --refresh")
		fmt.Fprintln(w, "        force refresh of the remote GeoJSON cache before running")
		fmt.Fprintln(w, "  --iterations int")
		fmt.Fprintf(w, "        maximum organic Koch iterations (0-%d)\n", koch.MaxIterations)
		fmt.Fprintln(w, "  --seed int")
		fmt.Fprintln(w, "        random seed for organic coastline generation")
		fmt.Fprintln(w, "  --angle-jitter float")
		fmt.Fprintln(w, "        maximum random angle deviation in degrees")
		fmt.Fprintln(w, "  --height-jitter float")
		fmt.Fprintln(w, "        maximum random height deviation as a ratio")
		fmt.Fprintln(w, "  --output string")
		fmt.Fprintln(w, "        output directory for generated visualizations (default: ./output)")
	}
}
