import { motion } from "motion/react";
import { BarChart3, Boxes, Fingerprint, Sparkles } from "lucide-react";

const signals = [
  { icon: Boxes, value: "4 слоя", label: "данные → модель → расчёт → отчёт" },
  { icon: BarChart3, value: "12+ метрик", label: "для контроля качества результата" },
  { icon: Fingerprint, value: "1 паспорт", label: "для воспроизводимости запуска" },
];

export function ProjectPulse() {
  return <section className="grid gap-5 lg:grid-cols-[0.8fr_1.2fr] lg:items-stretch"><div className="relative overflow-hidden rounded-2xl bg-zinc-950 p-6 text-zinc-100 sm:p-8"><motion.div animate={{ rotate: 360 }} transition={{ duration: 24, repeat: Infinity, ease: "linear" }} className="absolute -right-20 -bottom-24 size-64 rounded-full border border-cyan-400/20 border-dashed" /><div className="relative"><div className="mb-8 flex items-center gap-2 text-cyan-300"><Sparkles className="size-4" /> Внутри проекта</div><p className="font-mono text-sm leading-7 text-zinc-400">$ lito seabed check-full</p><div className="mt-5 space-y-3 font-mono text-sm"><p className="text-emerald-400">✓ coastline geometry      verified</p><p className="text-emerald-400">✓ bathymetry source        trusted</p><p className="text-emerald-400">✓ adaptive mesh            accepted</p><p className="text-cyan-300">→ reproducible report       ready</p></div></div></div><div className="rounded-2xl border bg-muted/20 p-5 sm:p-8"><p className="text-xs font-medium tracking-[0.2em] text-primary uppercase">Сигналы качества</p><h2 className="mt-2 text-2xl font-bold sm:text-3xl">Каждый результат можно объяснить</h2><p className="mt-3 leading-7 text-muted-foreground">Litora не прячет вычисления за одной кнопкой. Структура данных, параметры запуска и контрольные метрики остаются частью результата.</p><div className="mt-7 grid gap-3 sm:grid-cols-3">{signals.map((signal, index) => { const Icon = signal.icon; return <motion.div key={signal.value} whileHover={{ y: -4 }} transition={{ type: "spring", stiffness: 300 }} className="rounded-xl border bg-background p-4"><Icon className="mb-5 size-5 text-primary" /><strong className="block text-lg">{signal.value}</strong><span className="mt-1 block text-xs leading-5 text-muted-foreground">{signal.label}</span><div className="mt-4 h-1 overflow-hidden rounded-full bg-muted"><motion.div initial={{ width: 0 }} whileInView={{ width: `${55 + index * 18}%` }} viewport={{ once: true }} transition={{ duration: 0.8, delay: index * 0.15 }} className="h-full rounded-full bg-primary" /></div></motion.div>; })}</div></div></section>;
}
